import { beatsToSpawnTime, Song } from './song';

export const autumnDance: Song = beatsToSpawnTime({
  name: 'autumn-dance',
  source: 'music/autumn_dance.mp3',
  baseArrowSpeed: 1.6,
  bpm: 106 / 2,
  notes: [
    // Section 1: only bass and snare
    { time: 0, direction: 'left' },
    { time: 0, direction: 'up' },
    { time: 0.5, direction: 'right' },
    { time: 1, direction: 'down' },
    { time: 2, direction: 'left' },
    { time: 2, direction: 'up' },
    { time: 2.25, direction: 'down' },
    { time: 2.75, direction: 'right' },
    { time: 4, direction: 'right' },
    { time: 4, direction: 'up' },
    { time: 4.5, direction: 'left' },
    { time: 5, direction: 'down' },
    { time: 6, direction: 'right' },
    { time: 6, direction: 'up' },
    { time: 6.25, direction: 'down' },
    { time: 6.75, direction: 'left' },
    { time: 8, direction: 'left' },
    { time: 8, direction: 'up' },
    { time: 8.5, direction: 'right' },
    { time: 9, direction: 'down' },
    { time: 10, direction: 'left' },
    { time: 10, direction: 'up' },
    { time: 10.25, direction: 'down' },
    { time: 10.75, direction: 'right' },

    // Section 2: electronic sounds added
    { time: 12, direction: 'right' },
    { time: 12.5, direction: 'left' },
    { time: 13.25, direction: 'right' },
    { time: 14, direction: 'left' },
    { time: 14.75, direction: 'right' },
    { time: 15.25, direction: 'left' },
    { time: 15.75, direction: 'down' },
    { time: 16, direction: 'right' },
    { time: 16.5, direction: 'left' },
    { time: 17.25, direction: 'right' },
    { time: 18, direction: 'left' },
    { time: 18.75, direction: 'right' },
    { time: 19.25, direction: 'left' },
    { time: 19.75, direction: 'down' },
    { time: 20, direction: 'right' },
    { time: 20.5, direction: 'left' },
    { time: 21.25, direction: 'right' },
    { time: 22, direction: 'left' },
    { time: 22.75, direction: 'right' },
    { time: 23.25, direction: 'left' },
    { time: 23.75, direction: 'down' },
    { time: 24, direction: 'right' },
    { time: 24.5, direction: 'left' },
    { time: 25.25, direction: 'right' },
    { time: 26, direction: 'left' },
    { time: 26.75, direction: 'right' },
    { time: 27.25, direction: 'left' },
    { time: 27.75, direction: 'down' },

    // Section 3: flute added
    { time: 28, direction: 'right' },
    { time: 29, direction: 'left' },
    { time: 30, direction: 'right' },
    { time: 31, direction: 'left' },
    { time: 32, direction: 'right' },
    { time: 33, direction: 'left' },
    { time: 34, direction: 'right' },
    { time: 35, direction: 'left' },
    { time: 36, direction: 'right' },
    { time: 37, direction: 'left' },
    { time: 38, direction: 'right' },
    { time: 39, direction: 'left' },
    { time: 40, direction: 'right' },
    { time: 41, direction: 'left' },
    { time: 42, direction: 'right' },
    { time: 43, direction: 'left' },
    { time: 44, direction: 'right' },
    { time: 45, direction: 'left' },
    { time: 46, direction: 'right' },
    { time: 47, direction: 'left' },
    { time: 48, direction: 'right' },
    { time: 49, direction: 'left' },
    { time: 50, direction: 'right' },
    { time: 51, direction: 'left' },
  ],
});
