import { beatsToSpawnTime, Song } from './song';

export const autumnDance: Song = beatsToSpawnTime({
  name: 'autumn-dance',
  source: 'music/autumn_dance.mp3',
  baseArrowSpeed: 1.6,
  bpm: 106 / 2,
  notes: [
    { time: 0, direction: 'left' },
    { time: 1, direction: 'right' },
    { time: 2, direction: 'left' },
    { time: 3, direction: 'right' },
    { time: 4, direction: 'left' },
    { time: 5, direction: 'right' },
    { time: 6, direction: 'left' },
    { time: 7, direction: 'right' },
    { time: 8, direction: 'right' },
    { time: 9, direction: 'left' },
    { time: 10, direction: 'right' },
    { time: 11, direction: 'left' },
    { time: 12, direction: 'right' },
    { time: 13, direction: 'left' },
    { time: 14, direction: 'right' },
    { time: 15, direction: 'left' },
    { time: 16, direction: 'right' },
    { time: 17, direction: 'left' },
    { time: 18, direction: 'right' },
    { time: 19, direction: 'left' },
    { time: 20, direction: 'right' },
    { time: 21, direction: 'left' },
    { time: 22, direction: 'right' },
    { time: 23, direction: 'left' },
    { time: 24, direction: 'right' },
    { time: 25, direction: 'left' },
    { time: 26, direction: 'right' },
    { time: 27, direction: 'left' },
    { time: 28, direction: 'right' },
    { time: 29, direction: 'left' },
    { time: 30, direction: 'right' },
    { time: 31, direction: 'left' },
    { time: 32, direction: 'right' },
    { time: 33, direction: 'left' },
    { time: 34, direction: 'right' },
    { time: 35, direction: 'left' },
    { time: 36, direction: 'right' },
    { time: 37, direction: 'left' },
    { time: 38, direction: 'right' },
    { time: 39, direction: 'left' },
    { time: 40, direction: 'right' },
    { time: 41, direction: 'left' },
    { time: 42, direction: 'right' },
    { time: 43, direction: 'left' },
    { time: 44, direction: 'right' },
    { time: 45, direction: 'left' },
    { time: 46, direction: 'right' },
    { time: 47, direction: 'left' },
    { time: 48, direction: 'right' },
    { time: 49, direction: 'left' },
    { time: 50, direction: 'right' },
    { time: 51, direction: 'left' },
  ],
});
